#!/bin/bash

xhost +SI:localuser:$USER

docker container run --rm -it -w "/home/x2go" \
    --user $(id -u) \
    --name x2go_client \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix" \
    --volume="$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR" \
    --env=DISPLAY \
    --env=XDG_RUNTIME_DIR \
    --network x2go \
    x2go \
    x2goclient
